# Generated by Django 5.0.6 on 2024-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drug', models.CharField(max_length=255)),
                ('drug_category', models.CharField(max_length=255)),
                ('drugbank_id', models.CharField(max_length=255)),
                ('target_or_mechanism_of_action', models.TextField()),
                ('kegg_drug_id', models.CharField(max_length=255)),
                ('drug_pubchem', models.CharField(max_length=255)),
                ('str_link_smiles', models.CharField(max_length=255)),
                ('single_or_combination', models.CharField(max_length=50)),
                ('pmid', models.CharField(max_length=255)),
                ('cancer_type', models.CharField(max_length=255)),
                ('cancer_type_description', models.TextField()),
                ('animal_strain_used', models.CharField(max_length=255)),
                ('cell_line_used_to_induce_tumor_in_mice', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('technique', models.CharField(max_length=255)),
                ('immune_system_function_enhanced', models.CharField(max_length=255)),
                ('immune_system_function_inhibited', models.CharField(max_length=255)),
                ('immune_system_function_unaffected', models.CharField(max_length=255)),
                ('negative_immune_system_regulation', models.CharField(max_length=255)),
                ('submitter_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('comment_or_suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CellStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drug', models.CharField(max_length=255)),
                ('drug_category', models.CharField(max_length=255)),
                ('drugbank_id', models.CharField(max_length=255)),
                ('target_or_mechanism_of_action', models.TextField()),
                ('kegg_drug_id', models.CharField(max_length=255)),
                ('pubchem_id', models.CharField(max_length=255)),
                ('str_link_smiles', models.CharField(max_length=255)),
                ('single_or_combination', models.CharField(max_length=50)),
                ('pmid', models.CharField(max_length=255)),
                ('cancer_type', models.CharField(max_length=255)),
                ('cancer_type_description', models.TextField()),
                ('system', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('technique', models.CharField(max_length=255)),
                ('immune_system_function_enhanced', models.CharField(max_length=255)),
                ('immune_system_function_inhibited', models.CharField(max_length=255)),
                ('immune_system_function_unaffected', models.CharField(max_length=255)),
                ('negative_immune_system_regulation', models.CharField(max_length=255)),
                ('submitter_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('comment_or_suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drug', models.CharField(max_length=255)),
                ('drug_category', models.CharField(max_length=255)),
                ('drugbank_id', models.CharField(max_length=255)),
                ('target_or_mechanism_of_action', models.TextField()),
                ('kegg_drug_id', models.CharField(max_length=255)),
                ('pubchem_id', models.CharField(max_length=255)),
                ('str_link_smiles', models.CharField(max_length=255)),
                ('single_or_combination', models.CharField(max_length=50)),
                ('pmid', models.CharField(max_length=255)),
                ('cancer_type', models.CharField(max_length=255)),
                ('cancer_type_description', models.TextField()),
                ('patient_sample', models.CharField(max_length=255)),
                ('male_or_female', models.CharField(max_length=6)),
                ('median_age_or_range', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('technique', models.CharField(max_length=255)),
                ('immune_system_function_enhanced', models.CharField(max_length=255)),
                ('immune_system_function_inhibited', models.CharField(max_length=255)),
                ('immune_system_function_unaffected', models.CharField(max_length=255)),
                ('negative_immune_system_regulation', models.CharField(max_length=255)),
                ('submitter_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('comment_or_suggestion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
